<Project>
    <PropertyGroup>
        <Version>0.0.1</Version>
        <AssemblyVersion>0.0.1</AssemblyVersion>
        <FileVersion>0.0.126.0904</FileVersion>
    </PropertyGroup>
    <PropertyGroup>
        <Authors>adv76</Authors>
        <Company>adv76</Company>
        <Product>JsonMergePatch</Product>
        <PackageTags>json;merge;patch;jsonmerge;jsonpatch;jsonmergepatch;json-merge;json-patch;json-merge-patch</PackageTags>
        <PackageProjectUrl>https://github.com/adv76/JsonMergePatch</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/adv76/JsonMergePatch/blob/master/LICENSE</PackageLicenseUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <Copyright>Copyright (c) 2026 adv76</Copyright>
        <RepositoryUrl>https://github.com/adv76/JsonMergePatch</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>
</Project>