<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>JsonMergePatch OpenAPI integration for ASP.NET Core.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>    

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Adv76.AspNetCore.JsonMergePatch\Adv76.AspNetCore.JsonMergePatch.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
      <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
    </ItemGroup>
    
</Project>
